# Generated by Django 3.0.4 on 2020-07-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('phone_no', models.IntegerField()),
                ('date_of_establishment', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Center')),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Center')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recovery_status', models.CharField(max_length=30)),
                ('beneficiary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Beneficiary')),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Center')),
            ],
        ),
    ]
