# Generated by Django 3.0.4 on 2020-07-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(max_length=90),
        ),
    ]
