# Generated by Django 3.0.4 on 2020-07-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_auto_20200725_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_txt', models.CharField(max_length=254)),
                ('category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('children_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Children')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_number', models.IntegerField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Center')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Question')),
            ],
        ),
    ]
